<?php


namespace App\Models;


use TPerformant\API\Filter\AffiliateProductFilter;
use TPerformant\API\Filter\AffiliateProductSort;
use TPerformant\API\HTTP\User;

class ProductFeed extends \TPerformant\API\Model\ProductFeed
{

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }


    /**
     * @return mixed
     */
    public function getProgram()
    {
        return $this->program;
    }


    /**
     * @return mixed
     */
    public function getProductsCount()
    {
        return $this->productsCount;
    }


    public function products(AffiliateProductFilter $filter = null, AffiliateProductSort $sort = null)
    {
        return parent::products($filter, $sort); // TODO: Change the autogenerated stub
    }



}
